name: Bug Report
description: Something isn't working right on the website
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Something broken? Let us know! Just describe what happened.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what went wrong
      placeholder: "Example: I tried to book a private lesson but the calendar didn't show any available times"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "Example: I expected to see available time slots for the instructor"
    validations:
      required: false

  - type: dropdown
    id: device
    attributes:
      label: What device were you using?
      options:
        - Phone (iPhone)
        - Phone (Android)
        - Tablet / iPad
        - Laptop / Desktop
        - Not sure
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot or screen recording
      description: If you can, take a screenshot or screen recording showing the problem
      placeholder: "Drag and drop images or videos here"
    validations:
      required: false
